version: 2

jobs:
  build:
    working_directory: ~/pack
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            yarn global add codecov
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: test
          command: ./node_modules/.bin/nyc yarn test
      - run:
          name: Upload code coverage
          command: |
            ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
            ./node_modules/.bin/codecov
          when: on_success
